"""add_image_data_columns

Revision ID: 26c432a958c4
Revises: ced1aad96e64
Create Date: 2026-08-08 14:55:44.402951

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '26c432a958c4'
down_revision: Union[str, Sequence[str], None] = 'ced1aad96e64'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_threads', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chat_threads_created_at'), ['created_at'], unique=False)

    with op.batch_alter_table('files', schema=None) as batch_op:
        batch_op.add_column(sa.Column('file_data', sa.Text(), nullable=True))

    with op.batch_alter_table('pages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_data', sa.Text(), nullable=True))

    with op.batch_alter_table('photos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_data', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('photos', schema=None) as batch_op:
        batch_op.drop_column('image_data')

    with op.batch_alter_table('pages', schema=None) as batch_op:
        batch_op.drop_column('image_data')

    with op.batch_alter_table('files', schema=None) as batch_op:
        batch_op.drop_column('file_data')

    with op.batch_alter_table('chat_threads', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chat_threads_created_at'))

    # ### end Alembic commands ###
