"""voters_section_name_to_text

Revision ID: 7743375bcf7b
Revises: 26c432a958c4
Create Date: 2026-08-08 15:12:15.479360

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7743375bcf7b'
down_revision: Union[str, Sequence[str], None] = '26c432a958c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('voters', schema=None) as batch_op:
        batch_op.alter_column('section_name',
               existing_type=sa.VARCHAR(length=512),
               type_=sa.Text(),
               existing_nullable=False,
               existing_server_default=sa.text("''::character varying"))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('voters', schema=None) as batch_op:
        batch_op.alter_column('section_name',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=512),
               existing_nullable=False,
               existing_server_default=sa.text("''::character varying"))

    # ### end Alembic commands ###
