"""baseline schema

The schema as it stood when alembic was introduced, generated against an
empty database so it can build one from nothing.

Databases that predate this revision are *stamped* with it rather than
having it applied -- their tables already exist. See
`app.db._adopt_pre_alembic_database`.

Revision ID: a46b568717b8
Revises: 
Create Date: 2026-07-28 17:17:45.370365

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a46b568717b8'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('voter_id', sa.String(length=32), nullable=True),
    sa.Column('file_id', sa.String(length=32), nullable=True),
    sa.Column('page_id', sa.String(length=32), nullable=True),
    sa.Column('action', sa.String(length=32), nullable=False),
    sa.Column('field_name', sa.String(length=128), nullable=False),
    sa.Column('old_value', sa.Text(), nullable=True),
    sa.Column('new_value', sa.Text(), nullable=True),
    sa.Column('user_id', sa.String(length=128), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_file_id'), ['file_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_page_id'), ['page_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_timestamp'), ['timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_voter_id'), ['voter_id'], unique=False)

    op.create_table('files',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=512), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('page_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('pages_done', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.String(length=64), nullable=True),
    sa.Column('languages', sa.JSON(), nullable=False),
    sa.Column('stored_path', sa.String(length=1024), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('files', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_files_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_files_status'), ['status'], unique=False)

    op.create_table('jobs',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('file_ids', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('total_pages', sa.Integer(), nullable=False),
    sa.Column('completed_pages', sa.Integer(), nullable=False),
    sa.Column('failed_pages', sa.Integer(), nullable=False),
    sa.Column('current_item', sa.String(length=512), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_jobs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_jobs_status'), ['status'], unique=False)

    op.create_table('photos',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('file_id', sa.String(length=32), nullable=True),
    sa.Column('page_id', sa.String(length=32), nullable=True),
    sa.Column('record_id', sa.String(length=32), nullable=True),
    sa.Column('voter_id', sa.String(length=32), nullable=True),
    sa.Column('polling_station_id', sa.String(length=32), nullable=True),
    sa.Column('photo_type', sa.String(length=64), nullable=False),
    sa.Column('file_path', sa.String(length=1024), nullable=False),
    sa.Column('width', sa.Integer(), nullable=False),
    sa.Column('height', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('photos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_photos_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_photos_file_id'), ['file_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_photos_page_id'), ['page_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_photos_photo_type'), ['photo_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_photos_polling_station_id'), ['polling_station_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_photos_record_id'), ['record_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_photos_voter_id'), ['voter_id'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('username', sa.String(length=128), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=128), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('failed_attempts', sa.Integer(), nullable=False),
    sa.Column('locked_until', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('voters',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('epic', sa.String(length=32), nullable=False),
    sa.Column('serial', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('relation_type', sa.String(length=32), nullable=False),
    sa.Column('relation_name', sa.String(length=255), nullable=False),
    sa.Column('house_number', sa.String(length=64), nullable=False),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('gender', sa.String(length=16), nullable=False),
    sa.Column('part_number', sa.String(length=32), nullable=False),
    sa.Column('constituency', sa.String(length=255), nullable=False),
    sa.Column('source_record_id', sa.String(length=32), nullable=True),
    sa.Column('source_page_id', sa.String(length=32), nullable=True),
    sa.Column('source_file_id', sa.String(length=32), nullable=True),
    sa.Column('source_file_name', sa.String(length=512), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=True),
    sa.Column('page_id', sa.String(length=32), nullable=True),
    sa.Column('polling_station_id', sa.String(length=32), nullable=True),
    sa.Column('is_supplement', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('search_text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=128), nullable=False),
    sa.Column('updated_by', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('voters', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_voters_age'), ['age'], unique=False)
        batch_op.create_index(batch_op.f('ix_voters_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_voters_epic'), ['epic'], unique=True)
        batch_op.create_index(batch_op.f('ix_voters_gender'), ['gender'], unique=False)
        batch_op.create_index(batch_op.f('ix_voters_is_supplement'), ['is_supplement'], unique=False)
        batch_op.create_index(batch_op.f('ix_voters_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_voters_page_id'), ['page_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_voters_part_number'), ['part_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_voters_polling_station_id'), ['polling_station_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_voters_search_text'), ['search_text'], unique=False)
        batch_op.create_index(batch_op.f('ix_voters_serial'), ['serial'], unique=False)
        batch_op.create_index(batch_op.f('ix_voters_source_file_id'), ['source_file_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_voters_verified'), ['verified'], unique=False)

    op.create_table('pages',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('file_id', sa.String(length=32), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('image_path', sa.String(length=512), nullable=True),
    sa.Column('width', sa.Integer(), nullable=False),
    sa.Column('height', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.String(length=64), nullable=True),
    sa.Column('template_confidence', sa.Float(), nullable=False),
    sa.Column('ocr_ms', sa.Integer(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('page_type', sa.String(length=64), nullable=False),
    sa.Column('classification_confidence', sa.Float(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['file_id'], ['files.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pages_file_id'), ['file_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_pages_page_number'), ['page_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_pages_page_type'), ['page_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_pages_status'), ['status'], unique=False)

    op.create_table('polling_stations',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('file_id', sa.String(length=32), nullable=False),
    sa.Column('part_number', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('name_tam', sa.String(length=255), nullable=False),
    sa.Column('building_name', sa.String(length=512), nullable=False),
    sa.Column('section_details', sa.Text(), nullable=False),
    sa.Column('total_electors', sa.Integer(), nullable=False),
    sa.Column('male_electors', sa.Integer(), nullable=False),
    sa.Column('female_electors', sa.Integer(), nullable=False),
    sa.Column('third_gender_electors', sa.Integer(), nullable=False),
    sa.Column('ac_number', sa.String(length=16), nullable=False),
    sa.Column('ac_name', sa.String(length=255), nullable=False),
    sa.Column('pc_number', sa.String(length=16), nullable=False),
    sa.Column('pc_name', sa.String(length=255), nullable=False),
    sa.Column('station_number', sa.String(length=16), nullable=False),
    sa.Column('station_type', sa.String(length=32), nullable=False),
    sa.Column('address', sa.Text(), nullable=False),
    sa.Column('district', sa.String(length=128), nullable=False),
    sa.Column('taluk', sa.String(length=128), nullable=False),
    sa.Column('pincode', sa.String(length=16), nullable=False),
    sa.Column('serial_start', sa.Integer(), nullable=True),
    sa.Column('serial_end', sa.Integer(), nullable=True),
    sa.Column('source_page_id', sa.String(length=32), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['file_id'], ['files.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('polling_stations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_polling_stations_ac_number'), ['ac_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_polling_stations_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_polling_stations_district'), ['district'], unique=False)
        batch_op.create_index(batch_op.f('ix_polling_stations_file_id'), ['file_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_polling_stations_part_number'), ['part_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_polling_stations_pincode'), ['pincode'], unique=False)
        batch_op.create_index(batch_op.f('ix_polling_stations_taluk'), ['taluk'], unique=False)

    op.create_table('sessions',
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('user_agent', sa.String(length=256), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('token')
    )
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sessions_expires_at'), ['expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_sessions_user_id'), ['user_id'], unique=False)

    op.create_table('summaries',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('file_id', sa.String(length=32), nullable=False),
    sa.Column('total_voters', sa.Integer(), nullable=False),
    sa.Column('male_count', sa.Integer(), nullable=False),
    sa.Column('female_count', sa.Integer(), nullable=False),
    sa.Column('third_gender_count', sa.Integer(), nullable=False),
    sa.Column('avg_age', sa.Float(), nullable=True),
    sa.Column('base_total', sa.Integer(), nullable=False),
    sa.Column('additions_total', sa.Integer(), nullable=False),
    sa.Column('deletions_total', sa.Integer(), nullable=False),
    sa.Column('corrections', sa.Integer(), nullable=False),
    sa.Column('extracted_records', sa.Integer(), nullable=False),
    sa.Column('printed_total', sa.Integer(), nullable=True),
    sa.Column('reconciled', sa.Boolean(), nullable=False),
    sa.Column('reconciliation_source', sa.String(length=16), nullable=False),
    sa.Column('source_page_id', sa.String(length=32), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['file_id'], ['files.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('summaries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_summaries_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_summaries_file_id'), ['file_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_summaries_reconciled'), ['reconciled'], unique=False)

    op.create_table('ocr_blocks',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('page_id', sa.String(length=32), nullable=False),
    sa.Column('record_id', sa.String(length=32), nullable=True),
    sa.Column('field_name', sa.String(length=64), nullable=False),
    sa.Column('bbox_x0', sa.Integer(), nullable=False),
    sa.Column('bbox_y0', sa.Integer(), nullable=False),
    sa.Column('bbox_x1', sa.Integer(), nullable=False),
    sa.Column('bbox_y1', sa.Integer(), nullable=False),
    sa.Column('raw_text', sa.Text(), nullable=False),
    sa.Column('corrected_text', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['page_id'], ['pages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ocr_blocks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ocr_blocks_page_id'), ['page_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ocr_blocks_record_id'), ['record_id'], unique=False)

    op.create_table('records',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('page_id', sa.String(length=32), nullable=False),
    sa.Column('file_id', sa.String(length=32), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=False),
    sa.Column('index', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.String(length=64), nullable=False),
    sa.Column('reviewed', sa.Boolean(), nullable=False),
    sa.Column('error_count', sa.Integer(), nullable=False),
    sa.Column('warning_count', sa.Integer(), nullable=False),
    sa.Column('mean_confidence', sa.Float(), nullable=False),
    sa.Column('min_confidence', sa.Float(), nullable=False),
    sa.Column('edited', sa.Boolean(), nullable=False),
    sa.Column('search_text', sa.Text(), nullable=False),
    sa.Column('fields', sa.JSON(), nullable=False),
    sa.Column('issues', sa.JSON(), nullable=False),
    sa.Column('bbox', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['page_id'], ['pages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_records_edited'), ['edited'], unique=False)
        batch_op.create_index(batch_op.f('ix_records_error_count'), ['error_count'], unique=False)
        batch_op.create_index(batch_op.f('ix_records_file_id'), ['file_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_records_mean_confidence'), ['mean_confidence'], unique=False)
        batch_op.create_index(batch_op.f('ix_records_page_id'), ['page_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_records_page_number'), ['page_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_records_reviewed'), ['reviewed'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_records_reviewed'))
        batch_op.drop_index(batch_op.f('ix_records_page_number'))
        batch_op.drop_index(batch_op.f('ix_records_page_id'))
        batch_op.drop_index(batch_op.f('ix_records_mean_confidence'))
        batch_op.drop_index(batch_op.f('ix_records_file_id'))
        batch_op.drop_index(batch_op.f('ix_records_error_count'))
        batch_op.drop_index(batch_op.f('ix_records_edited'))

    op.drop_table('records')
    with op.batch_alter_table('ocr_blocks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ocr_blocks_record_id'))
        batch_op.drop_index(batch_op.f('ix_ocr_blocks_page_id'))

    op.drop_table('ocr_blocks')
    with op.batch_alter_table('summaries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_summaries_reconciled'))
        batch_op.drop_index(batch_op.f('ix_summaries_file_id'))
        batch_op.drop_index(batch_op.f('ix_summaries_created_at'))

    op.drop_table('summaries')
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sessions_user_id'))
        batch_op.drop_index(batch_op.f('ix_sessions_expires_at'))

    op.drop_table('sessions')
    with op.batch_alter_table('polling_stations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_polling_stations_taluk'))
        batch_op.drop_index(batch_op.f('ix_polling_stations_pincode'))
        batch_op.drop_index(batch_op.f('ix_polling_stations_part_number'))
        batch_op.drop_index(batch_op.f('ix_polling_stations_file_id'))
        batch_op.drop_index(batch_op.f('ix_polling_stations_district'))
        batch_op.drop_index(batch_op.f('ix_polling_stations_created_at'))
        batch_op.drop_index(batch_op.f('ix_polling_stations_ac_number'))

    op.drop_table('polling_stations')
    with op.batch_alter_table('pages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pages_status'))
        batch_op.drop_index(batch_op.f('ix_pages_page_type'))
        batch_op.drop_index(batch_op.f('ix_pages_page_number'))
        batch_op.drop_index(batch_op.f('ix_pages_file_id'))

    op.drop_table('pages')
    with op.batch_alter_table('voters', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_voters_verified'))
        batch_op.drop_index(batch_op.f('ix_voters_source_file_id'))
        batch_op.drop_index(batch_op.f('ix_voters_serial'))
        batch_op.drop_index(batch_op.f('ix_voters_search_text'))
        batch_op.drop_index(batch_op.f('ix_voters_polling_station_id'))
        batch_op.drop_index(batch_op.f('ix_voters_part_number'))
        batch_op.drop_index(batch_op.f('ix_voters_page_id'))
        batch_op.drop_index(batch_op.f('ix_voters_name'))
        batch_op.drop_index(batch_op.f('ix_voters_is_supplement'))
        batch_op.drop_index(batch_op.f('ix_voters_gender'))
        batch_op.drop_index(batch_op.f('ix_voters_epic'))
        batch_op.drop_index(batch_op.f('ix_voters_created_at'))
        batch_op.drop_index(batch_op.f('ix_voters_age'))

    op.drop_table('voters')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))

    op.drop_table('users')
    with op.batch_alter_table('photos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_photos_voter_id'))
        batch_op.drop_index(batch_op.f('ix_photos_record_id'))
        batch_op.drop_index(batch_op.f('ix_photos_polling_station_id'))
        batch_op.drop_index(batch_op.f('ix_photos_photo_type'))
        batch_op.drop_index(batch_op.f('ix_photos_page_id'))
        batch_op.drop_index(batch_op.f('ix_photos_file_id'))
        batch_op.drop_index(batch_op.f('ix_photos_created_at'))

    op.drop_table('photos')
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_jobs_status'))
        batch_op.drop_index(batch_op.f('ix_jobs_created_at'))

    op.drop_table('jobs')
    with op.batch_alter_table('files', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_files_status'))
        batch_op.drop_index(batch_op.f('ix_files_created_at'))

    op.drop_table('files')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_voter_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_timestamp'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_page_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_file_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_action'))

    op.drop_table('audit_logs')
    # ### end Alembic commands ###
