"""add section_name to voters

Revision ID: ced1aad96e64
Revises: c7d8e9f0a1b2
Create Date: 2026-08-07 17:52:21.392938

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ced1aad96e64'
down_revision: Union[str, Sequence[str], None] = 'c7d8e9f0a1b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_threads', schema=None) as batch_op:
        pass

    with op.batch_alter_table('voters', schema=None) as batch_op:
        batch_op.add_column(sa.Column('section_name', sa.String(length=512), server_default='', nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('voters', schema=None) as batch_op:
        batch_op.drop_column('section_name')

    # `ix_chat_threads_created_at` is deliberately NOT dropped here. This
    # migration never creates it -- autogenerate emitted the drop because the
    # model already declared index=True while no migration had caught up. The
    # index is created and dropped by 26c432a958c4, which comes *after* this
    # revision, so dropping it here made every rollback past this point fail
    # with "index does not exist".

    # ### end Alembic commands ###
